### ISSUE TITLE
Extreme log spamming in large modpack

### ISSUE THREAD

**Issue by Rad586** [sisby-folk/crunchy-crunchy-advancements#1]
1.19.2 fabric
so it looks like this: 
https://gist.github.com/Rad233/b6509d65b8f5c58ec16f5fef2aac4803
yeah, it ends up working fine, 0 advancements are loaded, but it's just...too spamy

**Comment by sleepingdragoninn** [comment]
Can you reproduce this? the link is a 404 now. Sounds like an incompatibility with a specific mod, so a proper log on mclogs would help.

**Comment by Rad586** [comment]
The log spam looks like this: https://gist.github.com/Rad586/47c1765fd80680d1c0f8b885250f699e

**Comment by sleepingdragoninn** [comment]
Can you post a full latest.log uploaded to https://mclo.gs/ ?

**Comment by Rad586** [comment]
Sure
https://mclo.gs/lsL4A36

**Comment by sleepingdragoninn** [comment]
Here's a similar log: https://mclo.gs/Xw8eSyi

can you confirm this occurs in a vanilla world / on java 17? errors when loading custom worlds downloaded online aren't unexpected
