### ISSUE TITLE
how to configure?

### ISSUE THREAD

**Issue by ezio416** [sisby-folk/crunchy-crunchy-advancements#2]
The mod says it's fully configurable, however I don't see any way to do so. There's no config file, no commands, and no options in ModMenu. Is this only meant for modpack builders and not end-users? I'm just trying to hide/remove advancements in my singleplayer world that were added by other mods

Fabric 1.20.1

As a side-note, I would ask this question in your Discord, but the link on Modrinth is broken

**Comment by sleepingdragoninn** [comment]
there should be a toml file in config, but you may have to load a world once first. otherwise, this is a bug.

**Comment by ezio416** [comment]
Yeah sorry I guess I didn't notice the config file only being there after loading a world. Thank you!
